use crate::modules::ammdata::schemas::{
    SchemaCanonicalPoolEntry, SchemaFullCandleV1, SchemaMarketDefs, SchemaPoolCreationInfoV1,
    SchemaPoolSnapshot, SchemaTokenMetricsV1, Timeframe,
};
use crate::modules::ammdata::utils::activity::{ActivityIndexAcc, ActivityWriteAcc};
use crate::modules::ammdata::utils::candles::CandleCache;
use crate::schemas::SchemaAlkaneId;
use std::collections::{HashMap, HashSet};

pub struct IndexState {
    pub reserves_snapshot: HashMap<SchemaAlkaneId, SchemaPoolSnapshot>,
    pub pools_map: HashMap<SchemaAlkaneId, SchemaMarketDefs>,

    pub amm_factory_writes: Vec<(Vec<u8>, Vec<u8>)>,

    pub candle_cache: CandleCache,
    pub activity_acc: ActivityWriteAcc,
    pub index_acc: ActivityIndexAcc,

    pub canonical_pool_updates: HashMap<SchemaAlkaneId, Vec<SchemaCanonicalPoolEntry>>,
    pub canonical_trade_buckets: HashMap<SchemaAlkaneId, HashSet<(Timeframe, u64)>>,
    pub in_block_trade_volumes: HashMap<SchemaAlkaneId, (u128, u128)>,
    pub pools_touched: HashSet<SchemaAlkaneId>,
    pub has_trades: bool,

    pub pool_name_index_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub factory_pools_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_factory_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_creation_info_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_defs_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_metrics_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_metrics_index_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_metrics_index_deletes: Vec<Vec<u8>>,
    pub pool_metrics_index_new: u64,
    pub pool_lp_supply_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_details_snapshot_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub tvl_versioned_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_swaps_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_creations_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub address_pool_swaps_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub address_token_swaps_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub address_pool_creations_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub address_pool_mints_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub address_pool_burns_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub address_amm_history_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub amm_history_all_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_pools_writes: Vec<(Vec<u8>, Vec<u8>)>,

    pub token_metrics_cache: HashMap<SchemaAlkaneId, SchemaTokenMetricsV1>,
    pub alkane_label_cache: HashMap<SchemaAlkaneId, String>,
    pub pool_creation_info_cache: HashMap<SchemaAlkaneId, SchemaPoolCreationInfoV1>,

    pub token_metrics_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_metrics_index_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_metrics_index_deletes: Vec<Vec<u8>>,
    pub token_metrics_index_new: u64,
    pub token_search_index_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_search_index_deletes: Vec<Vec<u8>>,

    pub derived_metrics_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub derived_metrics_index_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub derived_metrics_index_deletes: Vec<Vec<u8>>,
    pub derived_metrics_index_new: HashMap<SchemaAlkaneId, u64>,
    pub derived_search_index_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub derived_search_index_deletes: Vec<Vec<u8>>,

    pub btc_usd_price: Option<u128>,
    pub btc_usd_price_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub canonical_pool_writes: Vec<(Vec<u8>, Vec<u8>)>,

    pub candle_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub pool_candle_overrides: HashMap<(SchemaAlkaneId, Timeframe, u64), SchemaFullCandleV1>,
    pub token_usd_candle_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_mcusd_candle_writes: Vec<(Vec<u8>, Vec<u8>)>,
    pub token_derived_usd_candle_writes: Vec<(Vec<u8>, Vec<u8>)>,
}

impl IndexState {
    pub fn new(
        reserves_snapshot: HashMap<SchemaAlkaneId, SchemaPoolSnapshot>,
        pools_map: HashMap<SchemaAlkaneId, SchemaMarketDefs>,
    ) -> Self {
        Self {
            reserves_snapshot,
            pools_map,
            amm_factory_writes: Vec::new(),
            candle_cache: CandleCache::new(),
            activity_acc: ActivityWriteAcc::new(),
            index_acc: ActivityIndexAcc::new(),
            canonical_pool_updates: HashMap::new(),
            canonical_trade_buckets: HashMap::new(),
            in_block_trade_volumes: HashMap::new(),
            pools_touched: HashSet::new(),
            has_trades: false,
            pool_name_index_writes: Vec::new(),
            factory_pools_writes: Vec::new(),
            pool_factory_writes: Vec::new(),
            pool_creation_info_writes: Vec::new(),
            pool_defs_writes: Vec::new(),
            pool_metrics_writes: Vec::new(),
            pool_metrics_index_writes: Vec::new(),
            pool_metrics_index_deletes: Vec::new(),
            pool_metrics_index_new: 0,
            pool_lp_supply_writes: Vec::new(),
            pool_details_snapshot_writes: Vec::new(),
            tvl_versioned_writes: Vec::new(),
            token_swaps_writes: Vec::new(),
            pool_creations_writes: Vec::new(),
            address_pool_swaps_writes: Vec::new(),
            address_token_swaps_writes: Vec::new(),
            address_pool_creations_writes: Vec::new(),
            address_pool_mints_writes: Vec::new(),
            address_pool_burns_writes: Vec::new(),
            address_amm_history_writes: Vec::new(),
            amm_history_all_writes: Vec::new(),
            token_pools_writes: Vec::new(),
            token_metrics_cache: HashMap::new(),
            alkane_label_cache: HashMap::new(),
            pool_creation_info_cache: HashMap::new(),
            token_metrics_writes: Vec::new(),
            token_metrics_index_writes: Vec::new(),
            token_metrics_index_deletes: Vec::new(),
            token_metrics_index_new: 0,
            token_search_index_writes: Vec::new(),
            token_search_index_deletes: Vec::new(),
            derived_metrics_writes: Vec::new(),
            derived_metrics_index_writes: Vec::new(),
            derived_metrics_index_deletes: Vec::new(),
            derived_metrics_index_new: HashMap::new(),
            derived_search_index_writes: Vec::new(),
            derived_search_index_deletes: Vec::new(),
            btc_usd_price: None,
            btc_usd_price_writes: Vec::new(),
            canonical_pool_writes: Vec::new(),
            candle_writes: Vec::new(),
            pool_candle_overrides: HashMap::new(),
            token_usd_candle_writes: Vec::new(),
            token_mcusd_candle_writes: Vec::new(),
            token_derived_usd_candle_writes: Vec::new(),
        }
    }
}
